[package]
name = "xmdx-core"
description = "xmdx core parsing utilities"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
markdown = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
